"use strict";

// Bob language identifiers. OpenAI receives their human-readable names in the
// prompt; it does not require provider-specific language codes.
var LANGUAGE_NAMES = {
  auto: "Auto-detected language",
  "zh-Hans": "Simplified Chinese",
  "zh-Hant": "Traditional Chinese",
  yue: "Cantonese",
  wyw: "Classical Chinese",
  pysx: "Pinyin abbreviation",
  en: "English",
  ja: "Japanese",
  ko: "Korean",
  fr: "French",
  de: "German",
  es: "Spanish",
  it: "Italian",
  ru: "Russian",
  pt: "Portuguese",
  "pt-pt": "Portuguese (Portugal)",
  "pt-br": "Portuguese (Brazil)",
  nl: "Dutch",
  pl: "Polish",
  ar: "Arabic",
  af: "Afrikaans",
  ak: "Akan",
  am: "Amharic",
  an: "Aragonese",
  as: "Assamese",
  ast: "Asturian",
  ay: "Aymara",
  az: "Azerbaijani",
  ba: "Bashkir",
  be: "Belarusian",
  bg: "Bulgarian",
  bho: "Bhojpuri",
  bi: "Bislama",
  bm: "Bambara",
  bn: "Bengali",
  bo: "Tibetan",
  br: "Breton",
  bs: "Bosnian",
  ca: "Catalan",
  ceb: "Cebuano",
  ch: "Chamorro",
  che: "Chechen",
  chr: "Cherokee",
  ckb: "Central Kurdish",
  co: "Corsican",
  cop: "Coptic",
  crh: "Crimean Tatar",
  cs: "Czech",
  cy: "Welsh",
  da: "Danish",
  dv: "Dhivehi",
  dz: "Dzongkha",
  ee: "Ewe",
  el: "Greek",
  eo: "Esperanto",
  et: "Estonian",
  eu: "Basque",
  fa: "Persian",
  fi: "Finnish",
  fil: "Filipino",
  fj: "Fijian",
  fo: "Faroese",
  fy: "Frisian",
  ga: "Irish",
  gd: "Scots Gaelic",
  gl: "Galician",
  gn: "Guarani",
  gu: "Gujarati",
  gv: "Manx",
  ha: "Hausa",
  haw: "Hawaiian",
  he: "Hebrew",
  hi: "Hindi",
  hmn: "Hmong",
  hr: "Croatian",
  ht: "Haitian Creole",
  hu: "Hungarian",
  hy: "Armenian",
  ia: "Interlingua",
  id: "Indonesian",
  ie: "Interlingue",
  ig: "Igbo",
  ilo: "Iloko",
  io: "Ido",
  is: "Icelandic",
  iu: "Inuktitut",
  jv: "Javanese",
  ka: "Georgian",
  kab: "Kabyle",
  kk: "Kazakh",
  kl: "Kalaallisut",
  km: "Khmer",
  kn: "Kannada",
  kr: "Kanuri",
  ks: "Kashmiri",
  ku: "Kurdish",
  kw: "Cornish",
  ky: "Kyrgyz",
  la: "Latin",
  lb: "Luxembourgish",
  lg: "Ganda",
  li: "Limburgish",
  ln: "Lingala",
  lo: "Lao",
  lt: "Lithuanian",
  lu: "Luba-Katanga",
  lv: "Latvian",
  mg: "Malagasy",
  mh: "Marshallese",
  mi: "Maori",
  mk: "Macedonian",
  ml: "Malayalam",
  mn: "Mongolian",
  mr: "Marathi",
  ms: "Malay",
  mt: "Maltese",
  my: "Myanmar (Burmese)",
  nb: "Norwegian Bokmal",
  nd: "North Ndebele",
  ne: "Nepali",
  no: "Norwegian",
  nr: "South Ndebele",
  nso: "Northern Sotho",
  nv: "Navajo",
  ny: "Nyanja",
  oc: "Occitan",
  om: "Oromo",
  or: "Odia",
  os: "Ossetian",
  pa: "Punjabi",
  ps: "Pashto",
  qu: "Quechua",
  rm: "Romansh",
  rn: "Rundi",
  ro: "Romanian",
  rw: "Kinyarwanda",
  sa: "Sanskrit",
  sd: "Sindhi",
  se: "Northern Sami",
  sg: "Sango",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  sm: "Samoan",
  sn: "Shona",
  so: "Somali",
  sq: "Albanian",
  sr: "Serbian",
  "sr-Cyrl": "Serbian (Cyrillic)",
  "sr-Latn": "Serbian (Latin)",
  ss: "Swati",
  st: "Sesotho",
  su: "Sundanese",
  sv: "Swedish",
  sw: "Swahili",
  ta: "Tamil",
  te: "Telugu",
  tg: "Tajik",
  th: "Thai",
  ti: "Tigrinya",
  tk: "Turkmen",
  tl: "Tagalog",
  tn: "Tswana",
  to: "Tongan",
  tr: "Turkish",
  ts: "Tsonga",
  tt: "Tatar",
  tw: "Twi",
  ug: "Uyghur",
  uk: "Ukrainian",
  ur: "Urdu",
  uz: "Uzbek",
  ve: "Venda",
  vi: "Vietnamese",
  vo: "Volapuk",
  wa: "Walloon",
  wo: "Wolof",
  xh: "Xhosa",
  yi: "Yiddish",
  yo: "Yoruba",
  zu: "Zulu"
};

function languageName(code) {
  if (LANGUAGE_NAMES[code]) {
    return LANGUAGE_NAMES[code];
  }
  return code || LANGUAGE_NAMES.auto;
}

function supportLanguages() {
  return Object.keys(LANGUAGE_NAMES);
}

module.exports = {
  LANGUAGE_NAMES: LANGUAGE_NAMES,
  languageName: languageName,
  supportLanguages: supportLanguages
};
